{% set name = "libcifpp" %}
{% set version = "7.0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PDB-REDO/libcifpp/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2297e6649a4f71caf9da5f1d97f59512e7324bb62083bb5b08eb00c1c0385cb3
  # patches:
  #   - macos_filesystem.patch  # [osx]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
  host:
    - eigen
    - libboost-devel
    - zlib

about:
  home: https://github.com/PDB-REDO/libcifpp
  license: BSD-2-Clause
  license_family: BSD
  summary: Library containing code to manipulate mmCIF and PDB files
  description: |
    This library contains code to work with mmCIF and PDB files.
  doc_url: https://github.com/PDB-REDO/libcifpp
  dev_url: https://github.com/PDB-REDO/libcifpp

extra:
  recipe-maintainers:
    - bkpoon
    - drlemmus
    - mhekkel
